unbind r
bind r source-file ~/.tmux.conf
bind-key -n C-x kill-pane
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
set -g mouse on
set-option -g status-position top
set -g window-status-format ' ⟨#{b:pane_current_path}:#W⟩ '
set -g window-status-current-format ' ⟨#{b:pane_current_path}:#W⟩ '
set -g status-interval 1
set -g window-status-current-style 'bg=green,fg=black'
set -g window-status-style 'bg=terminal,fg=white'
set -g status-left ''
set -g status-right '#[bg=terminal,fg=terminal] 🧠#(top -bn2 -d1 | grep "Cpu(s)" | tail -1 | awk "{printf \"%.0f%%\", 100-\$8}") #[bg=terminal,fg=terminal] 📥#(df -h / | awk "NR==2{print \$4}") #[bg=terminal,fg=terminal] ⏰#(uptime | sed "s/.*up *//;s/, *[0-9]* user.*//") #[bg=terminal,fg=terminal]#(ping -c1 -W1 google.fr >/dev/null 2>&1 && echo "🟢" || echo "🔴") '
set -g status-right-length 120
set -g status-style 'bg=terminal,fg=white'
set -g window-status-separator ' '
set -g monitor-activity on
set -g visual-activity off
set -g window-status-activity-style 'bg=colour236,fg=white'
